/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Game2.java
 *
 * Created on Jun 10, 2011, 5:50:28 PM
 */

package findthebomb;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Eng Omnia
 */
public class Game2 extends javax.swing.JApplet {
public void prepareLevelInterActive(JButton button,int cha,int hard){
    jLabel35.setIcon(button.getIcon());
     jDialog1.setSize(400, 400);
        jDialog1.setVisible(false);
        jFrame1.setVisible(false);
        JFrame frame= new JFrame();
        //  Label back = new Label("C:\\Users\\Eng Omnia\\Pictures\\project\\images.jpg");


        Board board = new Board();
        board.getPlayer().setTextField(jTextField2);

        board.setType(0);
        frame.add(board);
        board.setDialog(jDialog1);
        board.setFrame(frame);
        board.getPlayer().setDialog(jDialog2);
         board.getPlayer().setLabel(jLabel5);

          board.getPlayer().setName(jTextField3.getText());
        jDialog2.setSize(300, 200);
        board.getPlayer().setPlayer((ImageIcon) button.getIcon());
      if(hard==2){
            if(cha==0){
              cha=3;
          }
          board.getPlayer().setChallange(cha);
        
          board.prepareNormal();
      }
        if(hard==3){
         board.getPlayer().setChallange(10);
         board.getPlayer().setScore(10);
          board.prepareNormal();
        }
board.hard=hard;
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        frame.setSize(d.width,d.height);


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.setVisible(true);
}
    /** Initializes the applet Game2 */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jFrame4 = new javax.swing.JFrame();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton1.setText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton1);
        jButton1.setBounds(440, 320, 120, 49);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jTextField4);
        jTextField4.setBounds(20, 380, 133, 20);

        jLabel8.setText("Your Score");
        jDialog1.getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 350, 100, 14);

        jButton12.setText("show Score and Submit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton12);
        jButton12.setBounds(10, 320, 210, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Congratulations.png"))); // NOI18N
        jDialog1.getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, 0, 800, 410);

        jFrame1.setTitle("Find The bomb");
        jFrame1.getContentPane().setLayout(null);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babygirl.png"))); // NOI18N
        jButton2.setText("Easy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(10, 11, 210, 159);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/meduim.png"))); // NOI18N
        jButton3.setText("Meduim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(264, 13, 290, 155);

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setForeground(new java.awt.Color(0, 51, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hard.png"))); // NOI18N
        jButton4.setText("Hard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(80, 188, 376, 129);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 410, 379, 20);
        jFrame1.getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 360, 264, 20);

        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Enter your Name");
        jFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 340, 130, 14);

        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("enter the number of coins you challange to count ");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(114, 389, 389, 14);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton11.setText(" ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton11);
        jButton11.setBounds(570, 320, 130, 50);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blue_sky_windows_7_clipart.jpg"))); // NOI18N
        jLabel33.setText("jLabel33");
        jFrame1.getContentPane().add(jLabel33);
        jLabel33.setBounds(0, 0, 1310, 580);

        jFrame2.setTitle("How to Play");
        jFrame2.setMinimumSize(new java.awt.Dimension(700, 430));
        jFrame2.getContentPane().setLayout(null);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton13.setText(" ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton13);
        jButton13.setBounds(560, 280, 110, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/key.png"))); // NOI18N
        jFrame2.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 400);

        jFrame3.getContentPane().setLayout(null);

        jButton9.setText("Shortest Path");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton9);
        jButton9.setBounds(230, 94, 135, 23);

        jButton10.setText("just solve !! any Path");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton10);
        jButton10.setBounds(230, 170, 135, 23);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton19);
        jButton19.setBounds(299, 273, 130, 50);

        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Press enter to move from level to level");
        jFrame3.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 250, 301, 47);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blue_sky_windows_7_clipart.jpg"))); // NOI18N
        jLabel34.setText("jLabel34");
        jFrame3.getContentPane().add(jLabel34);
        jLabel34.setBounds(0, 0, 530, 380);

        jFrame4.getContentPane().setLayout(null);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton15.setText(" ");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton15);
        jButton15.setBounds(10, 270, 120, 50);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.png"))); // NOI18N
        jButton16.setText(" ");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton16);
        jButton16.setBounds(190, 270, 130, 50);

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setText("About the Game");
        jFrame4.getContentPane().add(jLabel10);
        jLabel10.setBounds(114, 27, 157, 21);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" You are in a building. Looks like a decrepit warehouse. Your stop-watch is ticking down");
        jFrame4.getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 92, 503, 14);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("What  happens at zero hour? Ah, you're here to rescue the victim of a kidnapping.");
        jFrame4.getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 117, 503, 14);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Your intelligence agency  says there's a bomb in the building, set to go off you know when");
        jFrame4.getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 142, 540, 14);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("You can either go to the victim and  attempt to rescue them in time, or you can go to the bomb and attempt to defuse it");
        jFrame4.getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 167, 667, 14);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("The sooner you  get to either, the more time you have to accomplish the task. ");
        jFrame4.getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 187, 601, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("What you must do is clear: go to  whichever you can get to first, the bomb or the victim.");
        jFrame4.getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 219, 601, 14);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" The bad guys have long since abandoned the  building, you should too if you value your life . . . but, duty calls");
        jFrame4.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 244, 699, 14);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house.png"))); // NOI18N
        jLabel18.setText(" ");
        jFrame4.getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 910, 300);

        jFrame5.getContentPane().setLayout(null);

        jLabel19.setFont(new java.awt.Font("Brush Script MT", 0, 18)); // NOI18N
        jLabel19.setText("..The game consists of 3 Levels ");
        jFrame5.getContentPane().add(jLabel19);
        jLabel19.setBounds(41, 28, 195, 23);

        jLabel20.setText("Easy");
        jFrame5.getContentPane().add(jLabel20);
        jLabel20.setBounds(26, 80, 100, 14);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("You just have to stop the bomb or save the victim");
        jFrame5.getContentPane().add(jLabel21);
        jLabel21.setBounds(46, 112, 350, 14);

        jLabel22.setText("Meduim");
        jFrame5.getContentPane().add(jLabel22);
        jLabel22.setBounds(26, 144, 170, 14);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("This level is a bit different your agency will not let you go until you deliver");
        jFrame5.getContentPane().add(jLabel23);
        jLabel23.setBounds(36, 169, 480, 14);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("certain amount of money .. you will be the one who define this amount");
        jFrame5.getContentPane().add(jLabel24);
        jLabel24.setBounds(36, 189, 510, 14);

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("Hard");
        jFrame5.getContentPane().add(jLabel25);
        jLabel25.setBounds(26, 221, 190, 14);

        jButton17.setText("Main menu");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton17);
        jButton17.setBounds(410, 370, 160, 23);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TAKE CARE OF YOUR STEPS !!");
        jFrame5.getContentPane().add(jLabel26);
        jLabel26.setBounds(36, 246, 390, 14);

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("you want to enter a blank tile ?? it's ok but if you enter it'll be blocked and you will not be longer");
        jFrame5.getContentPane().add(jLabel27);
        jLabel27.setBounds(26, 265, 570, 20);

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("to enter it again");
        jFrame5.getContentPane().add(jLabel28);
        jLabel28.setBounds(26, 291, 150, 14);

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("if you enter a grass tile your score will be reduced as long as you are on it so try to avoid this");
        jFrame5.getContentPane().add(jLabel29);
        jLabel29.setBounds(26, 316, 560, 14);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("it isn't all you will also have to excceed the number of coins defined bu your agency \"10\"");
        jFrame5.getContentPane().add(jLabel30);
        jLabel30.setBounds(20, 350, 490, 14);

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("you will initially have 10 coins");
        jFrame5.getContentPane().add(jLabel31);
        jLabel31.setBounds(20, 370, 447, 14);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house.png"))); // NOI18N
        jLabel32.setText("jLabel32");
        jFrame5.getContentPane().add(jLabel32);
        jLabel32.setBounds(0, 0, 580, 400);

        jDialog2.setForeground(new java.awt.Color(255, 255, 255));
        jDialog2.getContentPane().setLayout(null);

        jTextField2.setText("                       ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 110, 169, 20);

        jLabel4.setText("Score");
        jDialog2.getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 70, 60, 14);

        jLabel5.setText("Your Name");
        jDialog2.getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 52, 14);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hard.png"))); // NOI18N
        jDialog2.getContentPane().add(jLabel35);
        jLabel35.setBounds(230, 0, 190, 150);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-1.png"))); // NOI18N
        jButton18.setText(" ");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton18);
        jButton18.setBounds(179, 153, 120, 40);

        getContentPane().setLayout(null);

        jButton5.setText("Computer solve");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1180, 500, 140, 23);

        jButton6.setText("Play");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1180, 430, 140, 23);

        jButton7.setText("How to Play");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1180, 470, 140, 23);

        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1180, 540, 150, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        jLabel9.setText(" ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 0, 1404, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Game.getFrames()[0].setVisible(false);
        jFrame3.setSize(500,400);
        jFrame3.setVisible(true);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // Game.getFrames()[0].setVisible(false);
         //Game.getFrames()[0].add(jPanel1);
        jFrame1.setSize(600,500);
       jFrame1.setVisible(true);
       jFrame1.setEnabled(true);
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Game.getFrames()[0].setVisible(false);
        jFrame2.setSize(500,400);
        jFrame2.setVisible(true);
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


        jDialog1.setVisible(false);
        Game.getFrames()[0].setVisible(true);
        Game.getFrames()[0].setAlwaysOnTop(true);

        //jFrame1.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        jTextField4.setText(jTextField2.getText());
        try {
            HighScore.high(5, Integer.parseInt(jTextField2.getText()));
            HighScore.display();
        } catch (IOException ex) {
//            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.prepareLevelInterActive(jButton2,0,1);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int challange=0;
        try{
            challange=Integer.parseInt(jTextField1.getText());
        }catch(Exception e){

        }
        this.prepareLevelInterActive(jButton3,challange,2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.prepareLevelInterActive(jButton4,0,3);
}//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(false);
        Game.getFrames()[0].setVisible(true);
}//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(false);
}//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JFrame frame= new JFrame();
        //  Label back = new Label("C:\\Users\\Eng Omnia\\Pictures\\project\\images.jpg");
        jFrame3.setVisible(false);

        Board board = new Board();
        board.getPlayer().setDialog(jDialog1);

        //  board.setType(1);
        frame.add(board);
        board.setDialog(jDialog1);
        board.setFrame(frame);
        //board.getPlayer().setPlayer((ImageIcon) button.getIcon());
        board.shortestPath();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        frame.setSize(d.width,d.height);


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.setVisible(true);
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton10ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        Game.getFrames()[0].setVisible(true);
        jFrame3.setVisible(false);
}//GEN-LAST:event_jButton19ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jFrame4.setVisible(false);
}//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jFrame4.setVisible(false);
        jFrame5.setVisible(true);
        jFrame5.setSize(600,600);
}//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jFrame5.setVisible(false);
}//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
}//GEN-LAST:event_jButton18ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
